config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'base_pages#home'
  get 'home',      to: 'base_pages#home'
  get 'about',     to: 'base_pages#about'
  get 'contacts',  to: 'base_pages#contacts'
  get 'help',      to: 'base_pages#help'

  get '/login',    to: 'sessions#new'
  post 'login',    to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get '/signup',   to: 'users#new'
  resources        :users

  resources        :feeds

  # patch '/update/:id', to: 'feeds#update'
  # For details on the DSL available within this file,
  # see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
# frozen_string_literal: true

class Feed < ApplicationRecord
  has_and_belongs_to_many :users
  default_scope -> { order(created_at: :desc) }
  validates :user_ids, presence: true
  validates :link, presence: true
  validates :title, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_and_belongs_to_many :feeds, dependent: :destroy

  before_save { email.downcase! }
  validates :name, presence: true,
                   length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true,
                    length: { maximum: 250 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true

  has_secure_password
  validates :password, presence: true,
                       length: { minimum: 6 },
                       allow_nil: true

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/base_pages_controller.rb
# frozen_string_literal: true

class BasePagesController < ApplicationController
  def home; end

  def about; end

  def contacts; end

  def help; end
end

app/controllers/feeds_controller.rb
# frozen_string_literal: true

class FeedsController < ApplicationController
  before_action :logged_in_user, only: %i[index show create]

  def index
    @user = current_user
  end

  def show
    @feed = current_user.feeds.find_by_id(params[:id])
    update unless fresh_news(@feed)
    @rss = JSON.parse(@feed.rss)
  end

  def create
    if link_exist?(clearing_link_from_query(params[:link]))
      @feed = Feed.find_by(link: params[:link])
      current_user.feeds << @feed
      flash[:success] = 'You are add new feed, my congratulations!'
    else
      xml = RSS::Parser.parse(open(params[:link])).to_json
      @feed = current_user.feeds.build(title: params[:title],
                                       link: params[:link],
                                       rss: xml,
                                       update_rss_at: DateTime.now)
      @feed.user_ids = current_user.id
      if @feed.save
        flash[:success] = 'You are add new feed, my congratulations!'
      else
        flash[:danger] = 'Feel all fields!'
      end
    end
    redirect_to feeds_path
  end

  def destroy
    current_user.feeds.find_by_id(params[:id]).destroy
    flash[:success] = 'Feed deleted'
    redirect_to feeds_path
  end

  def update
    @feed = current_user.feeds.find_by_id(params[:id])
    xml = RSS::Parser.parse(open(@feed.link)).to_json
    @feed.update(rss: xml, update_rss_at: DateTime.now)
    redirect_to @feed
  end

  private

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = 'Please log in!!'
      redirect_to login_url
    end
  end

  def link_exist?(link)
    !Feed.find_by(link: link).nil?
  end

  def clearing_link_from_query(link)
    clear_link = URI.parse(link)
    clear_link.fragment = clear_link.query = nil
    clear_link.to_s
  end

  def fresh_news(feed)
    time_difference = (DateTime.now.to_f - feed.update_rss_at.to_f) / 86_400
    time_difference < 1
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      flash[:success] = 'Hello!'

      log_in user
      redirect_back_or user
    else
      flash[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[index edit update]
  before_action :correct_user,   only: %i[edit update]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'Welcome to the Sample App!'
      redirect_to @user
    else
      flash[:danger] = 'You make mistake!'
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'Profile updated!'
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = 'Please log in!!'
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'Ruby on Rails Tutorial Sample App'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/base_pages_helper.rb
# frozen_string_literal: true

module BasePagesHelper
end

app/helpers/feeds_helper.rb
# frozen_string_literal: true

module FeedsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user?(user)
    user && user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/base_pages/about.html.erb
<h1>BasePages#about</h1>
<p>Find me in app/views/base_pages/about.html.erb</p>

app/views/base_pages/contacts.html.erb
<h1>BasePages#contacts</h1>
<p>Find me in app/views/base_pages/contacts.html.erb</p>

app/views/base_pages/help.html.erb
<h1>BasePages#help</h1>
<p>Find me in app/views/base_pages/help.html.erb</p>

app/views/base_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>
  <h2>
    This is the home page for the
    <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("rails.svg", alt: "Rails logo", width: "200"), "https://rubyonrails.org/" %>

app/views/feeds/index.html.erb
<% provide(:title, "All feeds by #{@user.name}") %>
<%= render 'layouts/feed_form' %>

<div>

  <% if @user.feeds.count > 0 %>

    <h3>Feeds (<%= @user.feeds.count %>)</h3>
    <ol class="microposts">

      <% @user.feeds.each do |feed| %>
        <li>
          <span class="user"><%= feed.title %></span>
          <span class="content"><%= feed.link %></span>
          <span class="content pull-right">
            <span><%= link_to "Show news",
                                              feed,
                                              method: :get,
                                              class: "action btn btn-primary" %>
            </span>
            <span><%= link_to "Delete feed",
                                              feed,
                                              method: :delete,
                                              data: { confirm: "You sure?" },
                                              class: "btn btn-danger" %>
            </span>
          </span>
        </li>
      <% end %>

    </ol>
  <% end %>
</div>

app/views/feeds/show.html.erb
<% provide(:title, @feed.title) %>
<% if @rss.any? %>
  <h1><%= @rss['channel']['title'] %></h1>
  <h2><%= link_to @rss['channel']['link'], @rss['channel']['link'] %></h2>
  <h2>
    Last update <%= @feed.update_rss_at %>
    <%= button_to 'Update feed', feed_path, method: :patch, class: "btn btn-primary update-btn" %>
  </h2>

  <p<%= @rss['channel']['description'] %></p>
  <ul>
    <% @rss['channel']['item'].each do |item| %>
      <% obj =  OpenStruct.new(item) %>
      <li>
        <%= link_to obj.title, obj.link %>
        <p><%= obj.description %></p>
      </li>
    <% end %>
  </ul>
<% else %>
  <h2>Sorry, something wrong</h2>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_feed_form.html.erb
<%= form_with(model: @feed, local: true) do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>

  <%= f.label :link %>
  <%= f.text_area :link, placeholder: "Paste new link", class: 'form-control' %>

  <%= f.submit 'Add rss feed', class: "btn btn-primary" %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contacts_path %></li>
      <li><a href="https://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Feeds", feeds_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all',
                            'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'layouts/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:button_text, "Update user") %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, "Create user") %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.email %> <strong>|</strong> <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>